.PHONY: build run test migrate-up migrate-down

build:
	go build -o bin/ezra ./cmd/ezra

run:
	go run ./cmd/ezra

test:
	go test ./...

migrate-up:
	migrate -path migrations -database "$$DATABASE_URL" up

migrate-down:
	migrate -path migrations -database "$$DATABASE_URL" down

# Note: the old `make seed` target was removed. Cells are now lazily
# generated by cell.Seeder on first /map/cells request per 0.1° region.
# For manual warm-up, just hit the API:
#   curl 'http://HOST:PORT/api/v1/map/cells?lat=54.7353&lng=20.5519&radius_km=1.5'
